on:
  push:
    branches:
      - main
name: Deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: "git submodule update --init --recursive"
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: abatilo/actions-poetry@v2.1.6
      - run: poetry install
      - run: poetry run invoke build
      - uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          folder: output
