on:
  push:
    branches:
      - master
name: Deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: "git submodule update --init --recursive"
      - uses: abatilo/actions-poetry@1.0.3
        with:
          args: install
      - uses: abatilo/actions-poetry@1.0.3
        with:
          args: run invoke build
      - run: "touch output/.nojekyll"
      - uses: JamesIves/github-pages-deploy-action@2.0.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: output
          CNAME: nitori.org
