on:
  push:
    branches:
      - main
name: Deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: "git submodule update --init --recursive"
      - uses: actions/setup-python@v1
      - uses: abatilo/actions-poetry@v2.1.0
      - run: poetry install
      - run: poetry run invoke build
      - uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: output
          CNAME: nitori.org
